iter_freqs:
- - lowtheta
  - 3
  - 6
- - hightheta
  - 6
  - 12
- - beta
  - 13
  - 30
- - gamma
  - 30
  - 80
new_fs: 250
sake_index: index_verified.csv
search_path: C:/Users/panton01/Desktop/test_PAC
