iter_freqs:
- - lowtheta
  - 3
  - 6
- - hightheta
  - 6
  - 12
- - beta
  - 13
  - 30
- - gamma
  - 30
  - 80
- - highgamma
  - 80
  - 120
new_fs: 250
sake_index: index_verified.csv
search_path: //supercomputer2/Shared/Pantelis/hippo_lfp/full_time
