# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\sake_con_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1200, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(1200, 700))
        font = QtGui.QFont()
        font.setPointSize(12)
        mainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.errorBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.errorBrowser.setObjectName("errorBrowser")
        self.gridLayout.addWidget(self.errorBrowser, 6, 1, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.normCol = QtWidgets.QComboBox(self.centralwidget)
        self.normCol.setObjectName("normCol")
        self.gridLayout.addWidget(self.normCol, 2, 1, 1, 1)
        self.normCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.normCheckBox.setObjectName("normCheckBox")
        self.gridLayout.addWidget(self.normCheckBox, 2, 3, 1, 1)
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setMinimumSize(QtCore.QSize(300, 200))
        self.logoLabel.setMaximumSize(QtCore.QSize(202, 157))
        self.logoLabel.setText("")
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")
        self.gridLayout.addWidget(self.logoLabel, 6, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.pacFuncBox = QtWidgets.QComboBox(self.tab)
        self.pacFuncBox.setObjectName("pacFuncBox")
        self.gridLayout_2.addWidget(self.pacFuncBox, 2, 1, 1, 1)
        self.pacCalcButton = QtWidgets.QPushButton(self.tab)
        self.pacCalcButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pacCalcButton.sizePolicy().hasHeightForWidth())
        self.pacCalcButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pacCalcButton.setFont(font)
        self.pacCalcButton.setCheckable(False)
        self.pacCalcButton.setObjectName("pacCalcButton")
        self.gridLayout_2.addWidget(self.pacCalcButton, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.pacPlotButton = QtWidgets.QPushButton(self.tab)
        self.pacPlotButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pacPlotButton.sizePolicy().hasHeightForWidth())
        self.pacPlotButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pacPlotButton.setFont(font)
        self.pacPlotButton.setDefault(False)
        self.pacPlotButton.setFlat(False)
        self.pacPlotButton.setObjectName("pacPlotButton")
        self.gridLayout_2.addWidget(self.pacPlotButton, 3, 2, 1, 1)
        self.pacPlotBox = QtWidgets.QComboBox(self.tab)
        self.pacPlotBox.setObjectName("pacPlotBox")
        self.gridLayout_2.addWidget(self.pacPlotBox, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.coherCalcButton = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coherCalcButton.sizePolicy().hasHeightForWidth())
        self.coherCalcButton.setSizePolicy(sizePolicy)
        self.coherCalcButton.setObjectName("coherCalcButton")
        self.gridLayout_3.addWidget(self.coherCalcButton, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.coherFuncBox = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coherFuncBox.sizePolicy().hasHeightForWidth())
        self.coherFuncBox.setSizePolicy(sizePolicy)
        self.coherFuncBox.setObjectName("coherFuncBox")
        self.gridLayout_3.addWidget(self.coherFuncBox, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.coherPlotButton = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coherPlotButton.sizePolicy().hasHeightForWidth())
        self.coherPlotButton.setSizePolicy(sizePolicy)
        self.coherPlotButton.setObjectName("coherPlotButton")
        self.gridLayout_3.addWidget(self.coherPlotButton, 1, 2, 1, 1)
        self.coherPlotBox = QtWidgets.QComboBox(self.tab_2)
        self.coherPlotBox.setObjectName("coherPlotBox")
        self.gridLayout_3.addWidget(self.coherPlotBox, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 3, 0, 2, 4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.pathButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pathButton.setFont(font)
        self.pathButton.setObjectName("pathButton")
        self.gridLayout.addWidget(self.pathButton, 0, 3, 1, 1)
        self.normGroup = QtWidgets.QComboBox(self.centralwidget)
        self.normGroup.setObjectName("normGroup")
        self.gridLayout.addWidget(self.normGroup, 2, 2, 1, 1)
        self.pacBinEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pacBinEdit.setFont(font)
        self.pacBinEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pacBinEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pacBinEdit.setObjectName("pacBinEdit")
        self.gridLayout.addWidget(self.pacBinEdit, 1, 1, 1, 2)
        self.pathEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pathEdit.setFont(font)
        self.pathEdit.setObjectName("pathEdit")
        self.gridLayout.addWidget(self.pathEdit, 0, 0, 1, 3)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionSettings.setFont(font)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Sake Connectivity"))
        self.label_7.setText(_translate("mainWindow", "Normalize By:"))
        self.normCheckBox.setText(_translate("mainWindow", "Normalize"))
        self.label_4.setText(_translate("mainWindow", "PAC Function:"))
        self.pacCalcButton.setText(_translate("mainWindow", "Calculate PAC"))
        self.label_5.setText(_translate("mainWindow", "Plot Type:"))
        self.pacPlotButton.setText(_translate("mainWindow", " Plot PAC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Phase Amplitude Coupling"))
        self.coherCalcButton.setText(_translate("mainWindow", "Calculate Coherence"))
        self.label_3.setText(_translate("mainWindow", "Cohenrence Function:"))
        self.label_6.setText(_translate("mainWindow", "Plot Type:"))
        self.coherPlotButton.setText(_translate("mainWindow", "Plot Coherence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "Coherence"))
        self.label.setText(_translate("mainWindow", "Binning Window:"))
        self.label_2.setText(_translate("mainWindow", "(seconds)"))
        self.pathButton.setText(_translate("mainWindow", "Set Path"))
        self.pacBinEdit.setText(_translate("mainWindow", "30"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.actionSettings.setText(_translate("mainWindow", "Settings"))

